//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TryIt.CreateAccountService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CreateAccountService.ICreateAccountService")]
    public interface ICreateAccountService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreateAccountService/createAccount", ReplyAction="http://tempuri.org/ICreateAccountService/createAccountResponse")]
        bool createAccount(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreateAccountService/createAccount", ReplyAction="http://tempuri.org/ICreateAccountService/createAccountResponse")]
        System.Threading.Tasks.Task<bool> createAccountAsync(string username, string password);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICreateAccountServiceChannel : TryIt.CreateAccountService.ICreateAccountService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CreateAccountServiceClient : System.ServiceModel.ClientBase<TryIt.CreateAccountService.ICreateAccountService>, TryIt.CreateAccountService.ICreateAccountService {
        
        public CreateAccountServiceClient() {
        }
        
        public CreateAccountServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CreateAccountServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CreateAccountServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CreateAccountServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool createAccount(string username, string password) {
            return base.Channel.createAccount(username, password);
        }
        
        public System.Threading.Tasks.Task<bool> createAccountAsync(string username, string password) {
            return base.Channel.createAccountAsync(username, password);
        }
    }
}
